/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SchwerpunkteRouteImport } from './routes/schwerpunkte'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AusstattungRouteImport } from './routes/ausstattung'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SchwerpunkteRoute = SchwerpunkteRouteImport.update({
  id: '/schwerpunkte',
  path: '/schwerpunkte',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AusstattungRoute = AusstattungRouteImport.update({
  id: '/ausstattung',
  path: '/ausstattung',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ausstattung': typeof AusstattungRoute
  '/kontakt': typeof KontaktRoute
  '/schwerpunkte': typeof SchwerpunkteRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ausstattung': typeof AusstattungRoute
  '/kontakt': typeof KontaktRoute
  '/schwerpunkte': typeof SchwerpunkteRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ausstattung': typeof AusstattungRoute
  '/kontakt': typeof KontaktRoute
  '/schwerpunkte': typeof SchwerpunkteRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ausstattung' | '/kontakt' | '/schwerpunkte' | '/team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ausstattung' | '/kontakt' | '/schwerpunkte' | '/team'
  id: '__root__' | '/' | '/ausstattung' | '/kontakt' | '/schwerpunkte' | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AusstattungRoute: typeof AusstattungRoute
  KontaktRoute: typeof KontaktRoute
  SchwerpunkteRoute: typeof SchwerpunkteRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schwerpunkte': {
      id: '/schwerpunkte'
      path: '/schwerpunkte'
      fullPath: '/schwerpunkte'
      preLoaderRoute: typeof SchwerpunkteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ausstattung': {
      id: '/ausstattung'
      path: '/ausstattung'
      fullPath: '/ausstattung'
      preLoaderRoute: typeof AusstattungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AusstattungRoute: AusstattungRoute,
  KontaktRoute: KontaktRoute,
  SchwerpunkteRoute: SchwerpunkteRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
